#!/bin/bash

curl -L https://github.com/Etersoft/nxssh/tarball/master > nxssh.tar.gz
mkdir -p nxssh
cd nxssh
tar xz --strip-components=1  -f ../nxssh.tar.gz
for fn in patches/*; do
    patch -p1 < $fn
done
rm ../nxssh.tar.gz
