// $Id: SessionProperties_symbols.h 705 2012-03-16 13:01:13Z felfert $
//
// Copyright (C) 2011 The OpenNX team
// Author: Fritz Elfert
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU Library General Public License as
// published by the Free Software Foundation; either version 2 of the
// License, or (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU Library General Public
// License along with this program; if not, write to the
// Free Software Foundation, Inc.,
// 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
//

#define ID_DIALOG_PROPERTIES_SYMBOL_0 _("Session properties - OpenNX")
#define ID_DIALOG_PROPERTIES_SYMBOL_1 _("General")
#define ID_DIALOG_PROPERTIES_SYMBOL_2 _("Server")
#define ID_DIALOG_PROPERTIES_SYMBOL_3 _("Host")
#define ID_DIALOG_PROPERTIES_SYMBOL_4 _("Port")
#define ID_DIALOG_PROPERTIES_SYMBOL_5 _("Remember my password")
#define ID_DIALOG_PROPERTIES_SYMBOL_6 _("Key...")
#define ID_DIALOG_PROPERTIES_SYMBOL_7 _("Use SmartCard")
#define ID_DIALOG_PROPERTIES_SYMBOL_8 _("Desktop")
#define ID_DIALOG_PROPERTIES_SYMBOL_9 _("Unix")
#define ID_DIALOG_PROPERTIES_SYMBOL_10 _("Windows")
#define ID_DIALOG_PROPERTIES_SYMBOL_11 _("VNC")
#define ID_DIALOG_PROPERTIES_SYMBOL_12 _("Shadow")
#define ID_DIALOG_PROPERTIES_SYMBOL_13 _("KDE")
#define ID_DIALOG_PROPERTIES_SYMBOL_14 _("GNOME")
#define ID_DIALOG_PROPERTIES_SYMBOL_15 _("CDE")
#define ID_DIALOG_PROPERTIES_SYMBOL_16 _("XFCE")
#define ID_DIALOG_PROPERTIES_SYMBOL_17 _("XDMCP")
#define ID_DIALOG_PROPERTIES_SYMBOL_18 _("Custom")
#define ID_DIALOG_PROPERTIES_SYMBOL_19 _("Settings...")
#define ID_DIALOG_PROPERTIES_SYMBOL_20 _("MODEM")
#define ID_DIALOG_PROPERTIES_SYMBOL_21 _("ISDN")
#define ID_DIALOG_PROPERTIES_SYMBOL_22 _("ADSL")
#define ID_DIALOG_PROPERTIES_SYMBOL_23 _("WAN")
#define ID_DIALOG_PROPERTIES_SYMBOL_24 _("LAN")
#define ID_DIALOG_PROPERTIES_SYMBOL_25 _("Display and Keyboard")
#define ID_DIALOG_PROPERTIES_SYMBOL_26 _("640x480")
#define ID_DIALOG_PROPERTIES_SYMBOL_27 _("800x600")
#define ID_DIALOG_PROPERTIES_SYMBOL_28 _("1024x768")
#define ID_DIALOG_PROPERTIES_SYMBOL_29 _("Available Area")
#define ID_DIALOG_PROPERTIES_SYMBOL_30 _("Fullscreen")
#define ID_DIALOG_PROPERTIES_SYMBOL_31 _("W")
#define ID_DIALOG_PROPERTIES_SYMBOL_32 _("H")
#define ID_DIALOG_PROPERTIES_SYMBOL_33 _("Use custom settings")
#define ID_DIALOG_PROPERTIES_SYMBOL_34 _("Modify...")
#define ID_DIALOG_PROPERTIES_SYMBOL_35 _("Use custom layout")
#define ID_DIALOG_PROPERTIES_SYMBOL_36 _("Advanced")
#define ID_DIALOG_PROPERTIES_SYMBOL_37 _("Network")
#define ID_DIALOG_PROPERTIES_SYMBOL_38 _("Disable no-delay on TCP connection")
#define ID_DIALOG_PROPERTIES_SYMBOL_39 _("Disable ZLIB stream compression")
#define ID_DIALOG_PROPERTIES_SYMBOL_40 _("Enable SSL encryption of all traffic")
#define ID_DIALOG_PROPERTIES_SYMBOL_41 _("Connect through proxy")
#define ID_DIALOG_PROPERTIES_SYMBOL_42 _("System")
#define ID_DIALOG_PROPERTIES_SYMBOL_43 _("Disable DirectDraw rendering")
#define ID_DIALOG_PROPERTIES_SYMBOL_44 _("Grab keyboard when client has focus")
#define ID_DIALOG_PROPERTIES_SYMBOL_45 _("Disable deferred screen updates")
#define ID_DIALOG_PROPERTIES_SYMBOL_46 _("Clipboard filter")
#define ID_DIALOG_PROPERTIES_SYMBOL_47 _("Use PRIMARY selection")
#define ID_DIALOG_PROPERTIES_SYMBOL_48 _("Use CLIPBOARD selection")
#define ID_DIALOG_PROPERTIES_SYMBOL_49 _("Use both")
#define ID_DIALOG_PROPERTIES_SYMBOL_50 _("Cache")
#define ID_DIALOG_PROPERTIES_SYMBOL_51 _("In memory")
#define ID_DIALOG_PROPERTIES_SYMBOL_52 _("0 Mb")
#define ID_DIALOG_PROPERTIES_SYMBOL_53 _("1 Mb")
#define ID_DIALOG_PROPERTIES_SYMBOL_54 _("2 Mb")
#define ID_DIALOG_PROPERTIES_SYMBOL_55 _("4 Mb")
#define ID_DIALOG_PROPERTIES_SYMBOL_56 _("8 Mb")
#define ID_DIALOG_PROPERTIES_SYMBOL_57 _("16 Mb")
#define ID_DIALOG_PROPERTIES_SYMBOL_58 _("32 Mb")
#define ID_DIALOG_PROPERTIES_SYMBOL_59 _("64 Mb")
#define ID_DIALOG_PROPERTIES_SYMBOL_60 _("128 Mb")
#define ID_DIALOG_PROPERTIES_SYMBOL_61 _("On disk")
#define ID_DIALOG_PROPERTIES_SYMBOL_62 _("256 Mb")
#define ID_DIALOG_PROPERTIES_SYMBOL_63 _("512 Mb")
#define ID_DIALOG_PROPERTIES_SYMBOL_64 _("Clean all cache files")
#define ID_DIALOG_PROPERTIES_SYMBOL_65 _("Services")
#define ID_DIALOG_PROPERTIES_SYMBOL_66 _("Enable SMB sharing")
#define ID_DIALOG_PROPERTIES_SYMBOL_67 _("Default port")
#define ID_DIALOG_PROPERTIES_SYMBOL_68 _("Enable CUPS printing")
#define ID_DIALOG_PROPERTIES_SYMBOL_69 _("Add")
#define ID_DIALOG_PROPERTIES_SYMBOL_70 _("Modify")
#define ID_DIALOG_PROPERTIES_SYMBOL_71 _("Delete")
#define ID_DIALOG_PROPERTIES_SYMBOL_72 _("Enable multimedia support")
#define ID_DIALOG_PROPERTIES_SYMBOL_73 _("USB")
#define ID_DIALOG_PROPERTIES_SYMBOL_74 _("Enable USB forwarding")
#define ID_DIALOG_PROPERTIES_SYMBOL_75 _("Environment")
#define ID_DIALOG_PROPERTIES_SYMBOL_76 _("User NX directory")
#define ID_DIALOG_PROPERTIES_SYMBOL_77 _("...")
#define ID_DIALOG_PROPERTIES_SYMBOL_78 _("Remove old session files")
#define ID_DIALOG_PROPERTIES_SYMBOL_79 _("System NX directory")
#define ID_DIALOG_PROPERTIES_SYMBOL_80 _("System CUPS daemon")
#define ID_DIALOG_PROPERTIES_SYMBOL_81 _("System USBIP daemon")
#define ID_DIALOG_PROPERTIES_SYMBOL_82 _("Local command socket path")
#define ID_DIALOG_PROPERTIES_SYMBOL_83 _("Local port")
#define ID_DIALOG_PROPERTIES_SYMBOL_84 _("Create a desktop icon for this session")
#define ID_DIALOG_PROPERTIES_SYMBOL_85 _("Reset hidden messages")
#define ID_DIALOG_PROPERTIES_SYMBOL_86 _("Always use lowercase login name")
#define ID_DIALOG_PROPERTIES_SYMBOL_87 _("Clear password entry on abort")
#define ID_DIALOG_PROPERTIES_SYMBOL_88 _("Disable magic pixel in fullscreen mode")
#define ID_DIALOG_PROPERTIES_SYMBOL_89 _("About")
#define ID_DIALOG_PROPERTIES_SYMBOL_90 _("&Delete")
#define ID_DIALOG_PROPERTIES_SYMBOL_91 _("&Apply")
#define ID_DIALOG_PROPERTIES_SYMBOL_92 _("&OK")
#define ID_DIALOG_PROPERTIES_SYMBOL_93 _("&Cancel")
#define ID_DIALOG_PROPERTIES_SYMBOL_94 _("1280x1024")
#define ID_DIALOG_PROPERTIES_SYMBOL_95 _("1400x1050")
#define ID_DIALOG_PROPERTIES_SYMBOL_96 _("1440x900")
#define ID_DIALOG_PROPERTIES_SYMBOL_97 _("1680x1050")
#define ID_DIALOG_PROPERTIES_SYMBOL_98 _("1920x1080")
