#!/bin/sh

set -e

V=0.11.13
D=`pwd`

if [ $# != 2 ] ; then
    echo "Usage: buildopensc <prefix> <libdir>" >&2
    exit 1
fi
PFX=$1
LIBDEST=$2

CACHEDIR=$HOME/savebuild
CACHEDBUILD=$CACHEDIR/opensc-${V}-prebuild.tgz

fetch() {
	if [ -n "`which wget`" ] ; then
		wget $1
	else
		if [ -n "`which curl`" ] ; then
			curl -f -L -o `echo "$1"|sed -e 's!.*/\([^?]*\).*!\1!'` "$1"
		else
			echo "Need wget or curl" >&2
			exit 1
		fi
	fi
}

if [ -f $CACHEDBUILD ] ; then
	tar xzf $CACHEDBUILD
else
	fetch http://www.opensc-project.org/files/opensc/opensc-$V.tar.gz
	rm -rf opensc-$V
	tar xzf opensc-$V.tar.gz
	cd opensc-$V
	OPENSSL_CFLAGS="-I$D/dist$PFX/include" \
	OPENSSL_LIBS="-L$D/dist$PFX/lib -lcrypto" \
	CFLAGS="-arch ppc -arch i386" \
	LDLAGS="-arch ppc -arch i386" \
	./configure \
        	--prefix=$PFX \
        	--enable-pcsc \
        	--sysconfdir=/Library/OpenSC/etc \
        	--disable-static \
        	--disable-iconv \
        	--disable-readline \
        	--disable-dependency-tracking
	make
	rm -rf $D/dist
	mkdir $D/dist
	make DESTDIR=$D/dist install
	cd $D
	mkdir -p $CACHEDIR
	tar czf $CACHEDBUILD opensc-$V dist
fi
mkdir -p $LIBDEST
